---
version: "3"
services:
  db:
    container_name: db-cont
    build: ./database/
    command: trivy image database
    ports:
      - "3306:3306"

  auth:
    container_name: auth-cont
    build: ./auth/
    command: trivy image auth
    ports:
      - "5001:5001"

  book:
    container_name: book-cont
    build: ./book/
    command: trivy image book
    ports:
      - "5002:5002"

  borrow:
    container_name: borrow-cont
    build: ./borrow/
    command: trivy image borrow
    ports:
      - "5003:5003"

  app:
    container_name: app-cont
    build: .
    command: trivy image .
    ports:
      - "5000:5000"
